fix release workflow

diff --git a/.github/workflows/3.ModuleRelease.yml b/.github/workflows/3.ModuleRelease.yml
--- a/.github/workflows/3.ModuleRelease.yml
+++ b/.github/workflows/3.ModuleRelease.yml
@@ -14,19 +14,22 @@ on:
 jobs:
   check_previous_workflow:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion != 'success' }}
     steps:
-      - name: Echo failure message
-        run: echo "前一個工作流程[2.ModuleTest]失敗了。"
+      # 檢查上一個工作流程的狀態
+      - name: Check previous workflow status
+        id: check_status
+        run: |
+          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
+            echo "Previous workflow failed. Exiting."
+            exit 1
+          else
+            echo "Previous workflow succeeded. Continuing."
+          fi
 
   release:
     needs: check_previous_workflow
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-      - name: Echo success message
-        run: echo "前一個工作流程[2.ModuleTest]成功了。"
-
       # 下載前一工作流程的成品(artifact)
       - name: Download artifact
         uses: actions/download-artifact@v2
